{% set version = "0.7.7" %}
{% set name = "pynac" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.bz2
  url: https://github.com/pynac/pynac/releases/download/pynac-{{ version }}/pynac-{{ version }}.tar.bz2
  sha256: c7bab71c6f554e174cd507670d1435428cbb508b12d3423bf0960400fe8b2431

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - toolchain
    - libtool
    - pkg-config
    - python
    - gmp >=5.0.1,<7
    - mpfr 3.*
    - libflint 2.5.*
    - singular 4.1.0

  run:
    - python
    - gmp >=5.0.1,<7
    - mpfr 3.*
    - libflint 2.5.*
    - singular 4.1.0

test:
  commands:
    - test -f ${PREFIX}/include/pynac/ginac.h
    - test -f ${PREFIX}/lib/lib{{ name }}.a
    - test -f ${PREFIX}/lib/lib{{ name }}.dylib     # [osx]
    - test -f ${PREFIX}/lib/lib{{ name }}.so        # [linux]

about:
  home: http://pynac.org/
  license: GPLv2+
  license_file: COPYING
  summary: Pynac -- symbolic computation with Python objects
  dev_url: https://github.com/pynac/pynac

extra:
  recipe-maintainers:
    - isuruf
