{% set version = "0.7.16" %}
{% set name = "pynac" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.bz2
  url: https://github.com/pynac/pynac/releases/download/pynac-{{ version }}/pynac-{{ version }}.tar.bz2
  sha256: f68a3ff417cb268bd31df8d1dab7d5a542ab2ade883f1745306800de591f3b83
  patches:
    - memleak.patch
    - log_segfault.patch

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - libtool
  host:
    - pkg-config
    - python
    - gmp
    - mpfr
    - libflint 2.5.*
    - singular 4.1.0.p3
  run:
    - python
    - gmp
    - mpfr
    - libflint
    - singular 4.1.0.p3

test:
  commands:
    - test -f ${PREFIX}/include/pynac/ginac.h
    - test -f ${PREFIX}/lib/lib{{ name }}.a
    - test -f ${PREFIX}/lib/lib{{ name }}.dylib     # [osx]
    - test -f ${PREFIX}/lib/lib{{ name }}.so        # [linux]

about:
  home: http://pynac.org/
  license: GPLv2+
  license_file: COPYING
  summary: Pynac -- symbolic computation with Python objects
  dev_url: https://github.com/pynac/pynac

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
